version: "3.8"

services:
  client:
    container_name: client
    build:
      context: .
      dockerfile: ./apps/client/Dockerfile
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - VITE_API_URL=http://server:8080
    networks:
      - app_network

  server:
    container_name: server
    build:
      context: .
      dockerfile: ./apps/server/Dockerfile
    restart: always
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=development
    networks:
      - app_network

networks:
  app_network:
    driver: bridge