services:
  client:
    build:
      context: .
      dockerfile: apps/client/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./apps/client:/app/apps/client
      - /app/node_modules
    environment:
      - VITE_API_URL=http://server:8080
    depends_on:
      - server
    command: pnpm --filter @repo/client dev
  server:
    build:
      context: .
      dockerfile: apps/server/Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./apps/server:/app/apps/server
      - /app/node_modules
    command: pnpm --filter @repo/server dev